Repository prgrms-web-devcourse/FEDC4-deep-dive-study, pull requests merged in 2023-09, with the labels that each got.

#35 [39장] DOM - 2
  [26장]/영준.md
  [39장] DOM/승희.md
  [39장] DOM/효리.md
Labels: 39장

#37 [40장] 이벤트 -1
  [40장] 이벤트-1/혜수.md
Labels: 40장

#39 [40장] 이벤트 -2
  [26장] ES6 함수의 추가 기능/영준.md
  [33장] 7번째 데이터 타입 Symbol/영준.md
  [40장] 이벤트-2/영준.md
Labels: 40장

#41 [41장, 42장] 타이머, 비동기 프로그래밍
  [41장] 타이머/효리.md
  [42장] 비동기 프로그래밍/효리.md
Labels: 41장, 42장

#43 [43장, 44장] Ajax, REST API
  [43장] Ajax/승희.md
  [44장] REST API/승희.md
Labels: 43장, 44장
