Repository prgrms-web-devcourse/FEDC4-deep-dive-study, pull requests merged in 2023-07, with the labels that each got.

#13 [18장, 20장] 함수와 일급 객체, strict mode
  [18장] 함수와 일급 객체/효리.md
  [20장] strict mode/효리.md
Labels: 18장, 20장

#15 [19장] 프로토타입
  [19장] 프로토타입/승희.md
Labels: 19장

#17 docs: 21장, 22장 발표자료
  [21장] 빌트인 객체/주연.md
  [22장] this/주연.md
Labels: 21장, 22장
