Repository prgrms-web-devcourse/FEDC4-deep-dive-study, pull requests merged in 2023-08, with the labels that each got.

#25 [25장] 클래스-2
  [25장] 클래스-2/건우.md
Labels: 25장

#21 [24장] 클로저
  [24장] 클로저/종현.md
Labels: 24장

#23 [25장] 클래스-1
  [25장] 클래스-1/KakaoTalk_Photo_2023-08-02-01-17-51-1.jpeg
  [25장] 클래스-1/KakaoTalk_Photo_2023-08-02-01-17-51.jpeg
  [25장] 클래스-1/KakaoTalk_Photo_2023-08-02-01-25-05.jpeg
  [25장] 클래스-1/image.png
  [25장] 클래스-1/영준.md
Labels: 25장

#27 [26장, 33장] ES6 함수의 추가 기능, 7번째 데이터 타입 Symbol
  [26장] /영준.md
  [33장]/영준.md
Labels: 26장, 33장

#29 [34장, 35장, 36장] 이터러블, 스프레드 문법, 디스트럭처링 할당
  [34장, 35장, 36장] 이터러블, 스프레드 문법, 디스트럭처링 할당/주연.md
Labels: 34장, 35장, 36장

#31 [38장] 브라우저 렌더링 과정
  [38장] 브라우저 렌더링 과정/종현.md
Labels: 38장

#33 docs: [39장] DOM - 1
  [39장] DOM - 1/승희.md
Labels: 39장
