Repository prgrms-web-devcourse/FEDC4-deep-dive-study, pull requests merged in 2023-06, with the labels that each got.

#2 [1장] 프로그래밍
  .github/pull_request_template.md
  [1장] 프로그래밍 (예시)/주연.md
Labels: 1장

#3 [13장,14장] 스코프, 전역 변수의 문제점
  [13장] 스코프/주연.md
  [14장] 전역 변수의 문제점/주연.md
Labels: 13장, 14장

#4 [12장] 함수
  [12장] 함수/건우.md
Labels: 12장

#9 [15장, 37장] let, const 키워드와 블록 레벨 스코프, Set과 Map
  [15장]let, const 키워드와 블록 레벨 스코프/혜수.md
  [37장] Set과 Map/혜수.md
Labels: 15장, 37장

#5 [6, 7장] 데이터 타입, 연산자
  [6장] 데이터 타입/종현.md
  [7장] 연산자/종현.md
Labels: 6장, 7장

#6 [8, 9장] 제어문, 타입 변환과 단축 평가
  [8장] 제어문/효리.md
  [9장] 타입 변환과 단축 평가/효리.md
Labels: 8장, 9장

#7 [4, 5장] 변수, 표현식과 문
  [4장] 변수/image.png
  [4장] 변수/영준.md
  [5장] 표현식과 문/영준.md
Labels: 4장, 5장

#8 [10, 11장] 객체 리터럴, 원시 값과 객체의 비교
  [10장] 객체 리터럴/승희.md
  [11장] 원시 값과 객체의 비교/승희.md
Labels: 10장, 11장

#11 [16장,17장] 프로퍼티 어트리뷰트, 생성자 함수에 의한 객체 생성
  [16장] 프로퍼티 어트리뷰트/혜수.md
  [17장] 생성자 함수에 의한 객체 생성/혜수.md
Labels: 16장, 17장
